spring:
  application:
    name: discovery-server #match file name discovery-server.yml
  config:
    import: "configserver:http://host.docker.internal:10888"
  cloud:
    config:
      fail-fast: true